# Generated by Django 4.1.2 on 2023-03-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WriteUs',
            new_name='Appeal',
        ),
    ]
