# Generated by Django 4.1.2 on 2023-03-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_writeus_appeal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appeal',
            options={'verbose_name': 'Обращение', 'verbose_name_plural': 'Обращения'},
        ),
        migrations.RemoveField(
            model_name='appeal',
            name='phone',
        ),
        migrations.AlterField(
            model_name='appeal',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
